### ISSUE TITLE
Query code to edit graph view cannot be run

### ISSUE THREAD

**Issue by jametron** [terminusdb/terminusdb-tutorials#24]
It is not possible to create a view query once a graph of a WOQL.js query has been created. For example, in the [bike tutorial](https://terminusdb.com/blog/2020/01/14/my-first-terminusdb-graph-visualisation-bike-share-data/), the following query code throws an error Parse error: Syntax error Can't find variable: View

```
view = View.graph();
view.node("Start_Label", "End_Label").hidden(true)
view.node("End").icon({color: [255,0,0], unicode: "\uf84a"})
    .text("v:End_Label").size(25).charge(-10)
view.node("Start").icon({color: [255,0,0], unicode: "\uf84a"})
    .text("v:Start_Label").size(25).collisionRadius(10)
view.edge("Start", "End").weight(100)
```

**Comment by Cheukting** [comment]
> It is not possible to create a view query once a graph of a WOQL.js query has been created. For example, in the [bike tutorial](https://terminusdb.com/blog/2020/01/14/my-first-terminusdb-graph-visualisation-bike-share-data/), the following query code throws an error Parse error: Syntax error Can't find variable: View
> 
> ```
> view = View.graph();
> view.node("Start_Label", "End_Label").hidden(true)
> view.node("End").icon({color: [255,0,0], unicode: "\uf84a"})
>     .text("v:End_Label").size(25).charge(-10)
> view.node("Start").icon({color: [255,0,0], unicode: "\uf84a"})
>     .text("v:Start_Label").size(25).collisionRadius(10)
> view.edge("Start", "End").weight(100)
> ```

Hi, @jametron thanks for letting us know. The old view script was meant to be used in the console in TerminusDB 1.0

Now, we have the WOQLView in Python client we can maybe add the graph view example in Python in the Jupyter notebook example?
